### ISSUE TITLE
/home/liuyibing/policy_privacy/data/OPP-115/raw_data/

### ISSUE THREAD

**Issue by Yeorange3500** [BierOne/policy_privacy_benchmarks#1]
can you show me the raw_data folder? the link's folder donnot have vector

**Comment by BierOne** [comment]
Hi, Please reach out to the owner of [Polisis_Benchmark](https://github.com/SmartDataAnalytics/Polisis_Benchmark) repository to request access to the data. Thanks.

**Comment by Yeorange3500** [comment]
Thank you！And Do you have predict code file for this project‘s category
